# Generated by Django 5.0.4 on 2024-04-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50, null=True)),
                ('startTime', models.DateField(null=True)),
                ('endTime', models.DateField(null=True)),
                ('roomNo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('prerequisites', models.CharField(max_length=100, null=True)),
                ('instructor', models.CharField(max_length=50, null=True)),
                ('capacity', models.FloatField(null=True)),
                ('scheduleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.courseschedules')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.courses')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.students')),
            ],
        ),
    ]
