# Generated by Django 5.0.4 on 2024-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseschedules',
            name='days',
        ),
        migrations.AddField(
            model_name='courseschedules',
            name='days',
            field=models.ManyToManyField(to='register.day'),
        ),
    ]
